# SKIPI configuration
[General]
dns-server = system
ipv6 = false

prefer-ipv6 = false
[Rule]
FINAL,PROXY

[SKIPI]
profile-name = Default
profile-update-url = 
profile-update-locked = false
per-app-mode = global
sniffing = true
sniffing-route-only = true
mux = false
mux-concurrency = 8
mux-xudp-concurrency = 16
mux-udp-443 = 0
fragment = false
fragment-packets = tlshello
fragment-length = 100-200
fragment-interval = 10-20
vpn-local-dns = true
fake-dns = false
vpn-append-http-proxy = false
vpn-hev-tun = false
tun-mtu = 1500
tun-dns = 8.8.8.8
tun-ipv4-cidr = 172.19.0.1/30
tun-ipv6-cidr = fdfe:dcba:9876::1/126
network-activation = false
network-transport = wifi
resource-source = 0
resource-geoip-url = https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
resource-geosite-url = https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
resource-geoip-cn-private-url = https://github.com/v2fly/geoip/releases/latest/download/geoip-only-cn-private.dat
resource-direct-cidr-ipv4-url = https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt
resource-direct-cidr-ipv6-url = https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt
resource-user-agent = SKIPI/0.1.0/Android
