# SKIPI configuration
[General]
dns-server = https://1.1.1.1/dns-query
ipv6 = true

prefer-ipv6 = true
[Rule]
DOMAIN-SUFFIX,soundcloud,PROXY
DOMAIN-SET,geosite:category-ru,LTE RUS TORVALDS
DOMAIN-SET,geosite:private,DIRECT
FINAL,PROXY

[SKIPI]
profile-name = WIFI
profile-update-url = 
profile-update-locked = false
profile-auto-update = false
per-app-mode = blacklist
per-app-package = 0:ru.beeline.services
per-app-package = 0:ru.mts.mymts
sniffing = true
sniffing-route-only = true
mux = false
mux-concurrency = 8
mux-xudp-concurrency = 16
mux-udp-443 = 0
fragment = false
fragment-packets = tlshello
fragment-length = 100-200
fragment-interval = 10-20
vpn-local-dns = true
fake-dns = true
direct-dns-fallback-proxy = false
vpn-append-http-proxy = false
vpn-hev-tun = false
tun-mtu = 1500
tun-dns = 8.8.8.8
tun-ipv4-cidr = 172.19.0.1/30
tun-ipv6-cidr = fdfe:dcba:9876::1/126
proxy-dns = https://dns.adguard-dns.com/dns-query
direct-dns = https://1.1.1.1/dns-query,https://8.8.8.8/dns-query
network-activation = false
network-transport = wifi
resource-source = 3
resource-geoip-url = https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
resource-geosite-url = https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
resource-geoip-cn-private-url = https://github.com/v2fly/geoip/releases/latest/download/geoip-only-cn-private.dat
resource-direct-cidr-ipv4-url = https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt
resource-direct-cidr-ipv6-url = https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt
resource-user-agent = SKIPI/0.2.3/Android
resource-auto-update = true
resource-update-interval = 1
[Proxy Group]

LTE TORVALDS = url-test, 🇳🇱 Нидерланды | CDNVIDEO, 🇫🇮 Финляндия | CDNVIDEO, 🇳🇱 Нидерланды | ADS-01, 🇫🇮 Финляндия | ADS-03, 🇫🇮 Финляндия | ADS-04, 🇳🇱 Нидерланды | ADS-05, 🇫🇮 Финляндия | ADS-06, 🇳🇱 Нидерланды | ADS-07, 🇳🇱 Нидерланды | ADS-08, 🇫🇮 Финляндия | ADS-10, 🇫🇮 Финляндия | ADS-11, 🇳🇱 Нидерланды | ADS-12, 🇫🇮 Финляндия | ADS-13, 🇳🇱 Нидерланды | ADS-14, 🇳🇱 Нидерланды | ADS-15, 🇫🇮 Финляндия | ADS-17, 🇫🇮 Финляндия | ADS-18, 🇳🇱 Нидерланды | ADS-19, 🇫🇮 Финляндия | ADS-20, 🇳🇱 Нидерланды | ADS-21, 🇳🇱 Нидерланды | CDN-01, 🇫🇮 Финляндия | CDN-03, 🇫🇮 Финляндия | CDN-04, 🇳🇱 Нидерланды | CDN-05, 🇫🇮 Финляндия | CDN-06, 🇳🇱 Нидерланды | CDN-08, 🇫🇮 Финляндия | CDN-10, 🇫🇮 Финляндия | CDN-11, 🇳🇱 Нидерланды | CDN-12, 🇫🇮 Финляндия | CDN-13, 🇳🇱 Нидерланды | CDN-14, 🇳🇱 Нидерланды | CDN-15, 🇫🇮 Финляндия | CDN-17, 🇫🇮 Финляндия | CDN-18, 🇳🇱 Нидерланды | CDN-19, 🇫🇮 Финляндия | CDN-20, 🇳🇱 Нидерланды | CDN-21, 🇳🇱 Нидерланды | CDN-07, url=http://cp.cloudflare.com/generate_204, interval=15, skipi-display=always

WIFI TORVALDS = url-test, 🇳🇱 Нидерланды • Стабильный, 🇫🇮 Финляндия • Стабильный, 🇳🇱 Нидерланды • Быстрый, 🇫🇮 Финляндия • Быстрый, 🇳🇱 Нидерланды • Невидимый, 🇫🇮 Финляндия • Невидимый, 🇳🇱 Нидерланды • Маскировка, 🇳🇱 Нидерланды • Каскад, url=http://cp.cloudflare.com/generate_204, interval=15, skipi-display=always

LTE RUS TORVALDS = url-test, 🇷🇺 Россия • Быстрый, 🇷🇺 Россия • Маскировка (Yandex), 🇷🇺 Россия • Маскировка (VK), 🇷🇺 Россия • Обход (VK), 🇷🇺 Россия • Обход (YandexCloud), 🇷🇺 Россия | ADS-02, 🇷🇺 Россия | ADS-09, 🇷🇺 Россия | ADS-16, 🇷🇺 Россия | CDN-02, 🇷🇺 Россия | CDN-09, 🇷🇺 Россия | CDN-16, url=http://cp.cloudflare.com/generate_204, interval=15, skipi-display=active_config
  
